# Generated by Django 3.0.7 on 2020-06-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=32)),
                ('password2', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
