# Generated by Django 3.0.7 on 2020-06-28 05:54

import allotment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('no_col', models.IntegerField()),
                ('no_row', models.IntegerField()),
                ('total_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionmonth', models.CharField(choices=[('May-June', 'MAY-JUNE'), ('Dec-Jan', 'DEC-JAN')], default='May-June', max_length=11)),
                ('year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default='2020', max_length=11)),
                ('file', models.FileField(upload_to=allotment.models.content_file_name)),
                ('ttfile', models.FileField(default='0000000', upload_to=allotment.models.time_file_name)),
            ],
        ),
    ]
