# Generated by Django 3.0.7 on 2020-06-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionmonth', models.CharField(choices=[('May-Jun', 'May-Jun'), ('DEC-Jun', 'DEC-Jun')], max_length=11)),
                ('year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2022', '2022')], max_length=11)),
                ('file', models.FileField(upload_to='datafile')),
            ],
        ),
    ]
